/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#191c23",
        "tertiary-container": "#c55500",
        "primary-fixed-dim": "#adc7ff",
        "on-secondary-fixed-variant": "#2e4b57",
        "on-error": "#ffffff",
        "primary-fixed": "#d8e2ff",
        "surface-container-low": "#f2f3fd",
        "primary": "#005bbf",
        "surface-container-highest": "#e0e2ec",
        "error-container": "#ffdad6",
        "primary-container": "#1a73e8",
        "secondary-fixed-dim": "#adcbda",
        "on-secondary-container": "#4a6774",
        "error": "#ba1a1a",
        "surface-dim": "#d8d9e3",
        "inverse-surface": "#2d3038",
        "secondary": "#466270",
        "surface-bright": "#f9f9ff",
        "inverse-on-surface": "#eff0fa",
        "surface-variant": "#e0e2ec",
        "on-secondary-fixed": "#001f2a",
        "on-primary-fixed-variant": "#004493",
        "on-tertiary-fixed": "#341100",
        "surface-container-lowest": "#ffffff",
        "background": "#f9f9ff",
        "on-secondary": "#ffffff",
        "surface-container": "#ecedf7",
        "tertiary-fixed-dim": "#ffb691",
        "on-tertiary-fixed-variant": "#783100",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#c6e4f4",
        "on-error-container": "#93000a",
        "on-surface-variant": "#414754",
        "secondary-fixed": "#c9e7f7",
        "on-background": "#191c23",
        "tertiary": "#9e4300",
        "on-primary-fixed": "#001a41",
        "on-tertiary-container": "#0e0200",
        "surface-tint": "#005bc0",
        "outline-variant": "#c1c6d6",
        "inverse-primary": "#adc7ff",
        "tertiary-fixed": "#ffdbcb",
        "surface": "#f9f9ff",
        "on-primary-container": "#ffffff",
        "surface-container-high": "#e6e8f2",
        "outline": "#727785",
        "status-green-bg": "#E6F4EA",
        "status-green-text": "#137333",
        "status-red-bg": "#FCE8E6",
        "status-red-text": "#C5221F",
        "status-yellow-bg": "#FEF7E0",
        "status-yellow-text": "#B06000",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base_unit: "4px",
        card_padding: "16px",
        margin_mobile: "16px",
        gutter: "12px",
        stack_gap: "8px",
      },
      fontFamily: {
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "kpi-display": ["Manrope", "sans-serif"],
        "label-bold": ["Hanken Grotesk", "sans-serif"],
        "kpi-display-mobile": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "kpi-display": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-bold": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "kpi-display-mobile": ["36px", { lineHeight: "40px", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};
